version: "3"
services:
  mqtt-watchdog:
    container_name: mqtt-watchdog
    restart: always
    build: .
    ports:
      - "1883:1883"
      - "5000:80"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    environment:
      - "TZ=America/Argentina/Buenos_Aires"
volumes:
  mongodata:
